---
- name: create local user with hashed password
  hosts: local
  become: true
  vars:
  - user_password: $6$d64M7YKoIhD1/zFe$HcpG8YsUkhndE8oX7SAJXwanBnYp1Zu1/Wl8Y.PC5Vml057z11GnRieNAEBYGUVTk4zqwcjjvdi2fsW0SbffJ1
  tasks:
  - name: creating local user
    user:
     name: ammiraju
     password: "{{ user_password }}"
     uid: 1110
     comment: local user
     shell: /bin/bash
